name: deep-suppressor
channels:
    - conda-forge
    - pytorch
    - defaults
dependencies:
    - python=3.10
    - pip
    - cython
    - ipython
    - jupyter
    - jupyterlab
    - matplotlib
    - pandas
    - scikit-learn
    - scikit-image
    - seaborn
    - tqdm
    - pytorch
    - torchvision
    - torchaudio
    - torchtext
    - opencv
    - librosa
    - pip:
        - scipy
        - tensorboard
